import type { Resource, Patient, ResourceAgent } from "@/types";
import { computeTriageScore } from "./engine";

export function seedResources(): Resource[] {
  const now = Date.now();
  return [
    {
      id: "or-1",
      type: "OPERATING_ROOM",
      name: "OR-1",
      status: "AVAILABLE",
      location: "Floor 2, Wing A",
      capabilities: ["general", "cardiac", "trauma"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "or-2",
      type: "OPERATING_ROOM",
      name: "OR-2",
      status: "AVAILABLE",
      location: "Floor 2, Wing A",
      capabilities: ["general", "neurosurgery", "vascular"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "or-3",
      type: "OPERATING_ROOM",
      name: "OR-3",
      status: "MAINTENANCE",
      location: "Floor 2, Wing B",
      capabilities: ["general", "orthopedic"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "icu-1",
      type: "ICU_BED",
      name: "ICU Bed 1A",
      status: "AVAILABLE",
      location: "Floor 3, ICU Wing",
      capabilities: ["cardiac", "monitoring", "ventilation"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "icu-2",
      type: "ICU_BED",
      name: "ICU Bed 2A",
      status: "AVAILABLE",
      location: "Floor 3, ICU Wing",
      capabilities: ["monitoring", "ventilation", "sepsis"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "icu-3",
      type: "ICU_BED",
      name: "ICU Bed 3B",
      status: "OCCUPIED",
      location: "Floor 3, ICU Wing",
      capabilities: ["monitoring", "ventilation"],
      currentPatientId: null,
      utilizationHistory: Array(20).fill(1),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "eb-1",
      type: "EMERGENCY_BAY",
      name: "Emergency Bay 1",
      status: "AVAILABLE",
      location: "Floor 1, Emergency",
      capabilities: ["trauma", "resuscitation", "general"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "eb-2",
      type: "EMERGENCY_BAY",
      name: "Emergency Bay 2",
      status: "AVAILABLE",
      location: "Floor 1, Emergency",
      capabilities: ["cardiac", "resuscitation"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "vent-1",
      type: "VENTILATOR",
      name: "Ventilator A",
      status: "AVAILABLE",
      location: "Floor 3, ICU Wing",
      capabilities: ["ventilation", "respiratory"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "vent-2",
      type: "VENTILATOR",
      name: "Ventilator B",
      status: "AVAILABLE",
      location: "Floor 3, ICU Wing",
      capabilities: ["ventilation", "respiratory"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "ct-1",
      type: "CT_SCANNER",
      name: "CT Scanner 1",
      status: "AVAILABLE",
      location: "Floor 1, Imaging",
      capabilities: ["imaging", "neuro", "trauma"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "surgeon-1",
      type: "SURGEON",
      name: "Dr. Chen (Trauma)",
      status: "AVAILABLE",
      location: "Floor 2, Wing A",
      capabilities: ["trauma", "general", "vascular"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "surgeon-2",
      type: "SURGEON",
      name: "Dr. Patel (Cardiac)",
      status: "AVAILABLE",
      location: "Floor 2, Wing A",
      capabilities: ["cardiac", "thoracic"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "anesthesia-1",
      type: "ANESTHESIOLOGIST",
      name: "Dr. Kim (Anesthesia)",
      status: "AVAILABLE",
      location: "Floor 2, Wing A",
      capabilities: ["general", "cardiac", "neuro"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "nurse-icu-1",
      type: "NURSE_ICU",
      name: "RN Sarah (ICU)",
      status: "AVAILABLE",
      location: "Floor 3, ICU Wing",
      capabilities: ["monitoring", "ventilation", "cardiac"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "nurse-icu-2",
      type: "NURSE_ICU",
      name: "RN James (ICU)",
      status: "AVAILABLE",
      location: "Floor 3, ICU Wing",
      capabilities: ["monitoring", "sepsis"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "nurse-ed-1",
      type: "NURSE_ED",
      name: "RN Maria (ED)",
      status: "AVAILABLE",
      location: "Floor 1, Emergency",
      capabilities: ["trauma", "resuscitation", "triage"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "cardiologist-1",
      type: "CARDIOLOGIST",
      name: "Dr. Okonkwo (Cardiology)",
      status: "AVAILABLE",
      location: "Floor 2, Wing B",
      capabilities: ["cardiac", "ecg", "interventional"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "trauma-surgeon-1",
      type: "TRAUMA_SURGEON",
      name: "Dr. Reyes (Trauma Surgery)",
      status: "AVAILABLE",
      location: "Floor 2, Wing A",
      capabilities: ["trauma", "polytrauma", "vascular"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "defib-1",
      type: "DEFIBRILLATOR",
      name: "Defibrillator 1",
      status: "AVAILABLE",
      location: "Floor 1, Emergency",
      capabilities: ["cardiac", "resuscitation"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
  ];
}

function makeVitals(
  hr: number,
  sbp: number,
  dbp: number,
  rr: number,
  spo2: number,
  temp: number,
  gcs: number
) {
  return {
    heartRate: hr,
    systolicBP: sbp,
    diastolicBP: dbp,
    respiratoryRate: rr,
    oxygenSaturation: spo2,
    temperature: temp,
    consciousnessScore: gcs,
    timestamp: Date.now(),
  };
}

export function seedPatients(): Patient[] {
  const now = Date.now();

  const patientsRaw = [
    {
      id: "pt-1",
      mrn: "MRN-20847",
      age: 67,
      sex: "M" as const,
      condition: "CARDIAC_ARREST" as const,
      conditionDetails: "Witnessed cardiac arrest, CPR in progress",
      vitals: makeVitals(0, 0, 0, 0, 70, 36.5, 3),
      requiresResourceTypes: ["EMERGENCY_BAY", "DEFIBRILLATOR", "CARDIOLOGIST"] as Patient["requiresResourceTypes"],
      requiredCapabilities: ["cardiac", "resuscitation"],
      arrivedAt: now - 5 * 60000,
      estimatedTreatmentDuration: 120 * 60000,
    },
    {
      id: "pt-2",
      mrn: "MRN-31924",
      age: 45,
      sex: "M" as const,
      condition: "TRAUMA_MAJOR" as const,
      conditionDetails: "MVA — blunt chest trauma, suspected internal bleeding",
      vitals: makeVitals(120, 85, 55, 26, 93, 37.1, 12),
      requiresResourceTypes: ["OPERATING_ROOM", "TRAUMA_SURGEON", "ANESTHESIOLOGIST"] as Patient["requiresResourceTypes"],
      requiredCapabilities: ["trauma"],
      arrivedAt: now - 15 * 60000,
      estimatedTreatmentDuration: 180 * 60000,
    },
    {
      id: "pt-3",
      mrn: "MRN-44561",
      age: 58,
      sex: "F" as const,
      condition: "STROKE_ISCHEMIC" as const,
      conditionDetails: "Left-sided weakness, slurred speech, onset 45 min ago",
      vitals: makeVitals(88, 185, 105, 18, 96, 37.3, 13),
      requiresResourceTypes: ["CT_SCANNER", "ICU_BED"] as Patient["requiresResourceTypes"],
      requiredCapabilities: ["neuro", "monitoring"],
      arrivedAt: now - 25 * 60000,
      estimatedTreatmentDuration: 240 * 60000,
    },
    {
      id: "pt-4",
      mrn: "MRN-57832",
      age: 34,
      sex: "F" as const,
      condition: "SEPSIS" as const,
      conditionDetails: "Septic shock — high fever, low BP, altered mental status",
      vitals: makeVitals(115, 78, 45, 28, 91, 39.8, 11),
      requiresResourceTypes: ["ICU_BED", "NURSE_ICU"] as Patient["requiresResourceTypes"],
      requiredCapabilities: ["sepsis", "monitoring"],
      arrivedAt: now - 35 * 60000,
      estimatedTreatmentDuration: 300 * 60000,
    },
    {
      id: "pt-5",
      mrn: "MRN-60293",
      age: 22,
      sex: "M" as const,
      condition: "OVERDOSE" as const,
      conditionDetails: "Opioid overdose, responded to naloxone, monitoring required",
      vitals: makeVitals(55, 100, 65, 12, 95, 36.2, 14),
      requiresResourceTypes: ["EMERGENCY_BAY", "NURSE_ED"] as Patient["requiresResourceTypes"],
      requiredCapabilities: ["general"],
      arrivedAt: now - 45 * 60000,
      estimatedTreatmentDuration: 120 * 60000,
    },
  ];

  return patientsRaw.map((p) => ({
    ...p,
    triageScore: computeTriageScore(p.condition, p.vitals, p.arrivedAt),
    vitalsHistory: [p.vitals],
    status: "WAITING" as const,
    allocatedResources: [],
    dischargedAt: null,
    treatmentStartedAt: null,
  }));
}

export function seedAgents(resources: Resource[]): ResourceAgent[] {
  return resources.map((r) => ({
    id: `agent-${r.id}`,
    resourceId: r.id,
    state: r.status === "MAINTENANCE" ? ("MAINTENANCE" as const) : ("IDLE" as const),
    currentBid: null,
    currentPatientId: null,
    performanceMetrics: {
      totalAllocations: 0,
      bidsSubmitted: 0,
      bidsWon: 0,
      averageBidScore: 0,
    },
  }));
}

export function generateRandomPatient(): Omit<
  Patient,
  "triageScore" | "vitalsHistory" | "status" | "allocatedResources" | "treatmentStartedAt" | "dischargedAt"
> {
  const conditions = [
    "CARDIAC_ARREST",
    "TRAUMA_MAJOR",
    "STROKE_ISCHEMIC",
    "STROKE_HEMORRHAGIC",
    "SEPSIS",
    "RESPIRATORY_FAILURE",
    "BURNS_MAJOR",
    "POLYTRAUMA",
    "ANAPHYLAXIS",
    "OVERDOSE",
  ] as const;

  const resourceMap: Record<string, { types: string[]; caps: string[] }> = {
    CARDIAC_ARREST: {
      types: ["EMERGENCY_BAY", "DEFIBRILLATOR", "CARDIOLOGIST"],
      caps: ["cardiac", "resuscitation"],
    },
    TRAUMA_MAJOR: {
      types: ["OPERATING_ROOM", "TRAUMA_SURGEON", "ANESTHESIOLOGIST"],
      caps: ["trauma"],
    },
    STROKE_ISCHEMIC: { types: ["CT_SCANNER", "ICU_BED"], caps: ["neuro", "monitoring"] },
    STROKE_HEMORRHAGIC: {
      types: ["OPERATING_ROOM", "ICU_BED"],
      caps: ["neuro", "monitoring"],
    },
    SEPSIS: { types: ["ICU_BED", "NURSE_ICU"], caps: ["sepsis", "monitoring"] },
    RESPIRATORY_FAILURE: {
      types: ["ICU_BED", "VENTILATOR"],
      caps: ["ventilation", "respiratory"],
    },
    BURNS_MAJOR: {
      types: ["OPERATING_ROOM", "ICU_BED"],
      caps: ["trauma", "monitoring"],
    },
    POLYTRAUMA: {
      types: ["OPERATING_ROOM", "TRAUMA_SURGEON", "ICU_BED"],
      caps: ["trauma", "monitoring"],
    },
    ANAPHYLAXIS: { types: ["EMERGENCY_BAY", "NURSE_ED"], caps: ["resuscitation"] },
    OVERDOSE: { types: ["EMERGENCY_BAY", "NURSE_ED"], caps: ["general"] },
  };

  const condition = conditions[Math.floor(Math.random() * conditions.length)];
  const res = resourceMap[condition];
  const ages = [18, 25, 34, 45, 52, 61, 67, 73, 81];
  const mrnId = Math.floor(10000 + Math.random() * 90000);

  const vitals = makeVitals(
    50 + Math.floor(Math.random() * 100),
    60 + Math.floor(Math.random() * 120),
    40 + Math.floor(Math.random() * 60),
    8 + Math.floor(Math.random() * 24),
    80 + Math.floor(Math.random() * 20),
    35.5 + Math.random() * 4,
    3 + Math.floor(Math.random() * 13)
  );

  return {
    id: crypto.randomUUID(),
    mrn: `MRN-${mrnId}`,
    age: ages[Math.floor(Math.random() * ages.length)],
    sex: ["M", "F"][Math.floor(Math.random() * 2)] as "M" | "F",
    condition,
    conditionDetails: `${condition.replace(/_/g, " ")} — auto-generated patient`,
    vitals,
    requiresResourceTypes: res.types as Patient["requiresResourceTypes"],
    requiredCapabilities: res.caps,
    arrivedAt: Date.now(),
    estimatedTreatmentDuration: (60 + Math.floor(Math.random() * 240)) * 60000,
  };
}
