import type { Resource, Patient, ResourceAgent } from "@/types";
import { computeTriageScore } from "./engine";

export function seedResources(): Resource[] {
  const now = Date.now();
  return [
    {
      id: "or-1",
      type: "OPERATING_ROOM",
      name: "OR-1",
      status: "AVAILABLE",
      location: "Floor 2, Wing A",
      capabilities: ["general", "cardiac", "trauma"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "or-2",
      type: "OPERATING_ROOM",
      name: "OR-2",
      status: "AVAILABLE",
      location: "Floor 2, Wing A",
      capabilities: ["general", "neurosurgery", "vascular"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "or-3",
      type: "OPERATING_ROOM",
      name: "OR-3",
      status: "MAINTENANCE",
      location: "Floor 2, Wing B",
      capabilities: ["general", "orthopedic"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "icu-1",
      type: "ICU_BED",
      name: "ICU Bed 1A",
      status: "AVAILABLE",
      location: "Floor 3, ICU Wing",
      capabilities: ["cardiac", "monitoring", "ventilation"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "icu-2",
      type: "ICU_BED",
      name: "ICU Bed 2A",
      status: "AVAILABLE",
      location: "Floor 3, ICU Wing",
      capabilities: ["monitoring", "ventilation", "sepsis"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "icu-3",
      type: "ICU_BED",
      name: "ICU Bed 3B",
      status: "OCCUPIED",
      location: "Floor 3, ICU Wing",
      capabilities: ["monitoring", "ventilation"],
      currentPatientId: null,
      utilizationHistory: Array(20).fill(1),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "eb-1",
      type: "EMERGENCY_BAY",
      name: "Emergency Bay 1",
      status: "AVAILABLE",
      location: "Floor 1, Emergency",
      capabilities: ["trauma", "resuscitation", "general"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "eb-2",
      type: "EMERGENCY_BAY",
      name: "Emergency Bay 2",
      status: "AVAILABLE",
      location: "Floor 1, Emergency",
      capabilities: ["cardiac", "resuscitation"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "vent-1",
      type: "VENTILATOR",
      name: "Ventilator A",
      status: "AVAILABLE",
      location: "Floor 3, ICU Wing",
      capabilities: ["ventilation", "respiratory"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "vent-2",
      type: "VENTILATOR",
      name: "Ventilator B",
      status: "AVAILABLE",
      location: "Floor 3, ICU Wing",
      capabilities: ["ventilation", "respiratory"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "ct-1",
      type: "CT_SCANNER",
      name: "CT Scanner 1",
      status: "AVAILABLE",
      location: "Floor 1, Imaging",
      capabilities: ["imaging", "neuro", "trauma"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "surgeon-1",
      type: "SURGEON",
      name: "Dr. Chen (Trauma)",
      status: "AVAILABLE",
      location: "Floor 2, Wing A",
      capabilities: ["trauma", "general", "vascular"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "surgeon-2",
      type: "SURGEON",
      name: "Dr. Patel (Cardiac)",
      status: "AVAILABLE",
      location: "Floor 2, Wing A",
      capabilities: ["cardiac", "thoracic"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "anesthesia-1",
      type: "ANESTHESIOLOGIST",
      name: "Dr. Kim (Anesthesia)",
      status: "AVAILABLE",
      location: "Floor 2, Wing A",
      capabilities: ["general", "cardiac", "neuro"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "nurse-icu-1",
      type: "NURSE_ICU",
      name: "RN Sarah (ICU)",
      status: "AVAILABLE",
      location: "Floor 3, ICU Wing",
      capabilities: ["monitoring", "ventilation", "cardiac"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "nurse-icu-2",
      type: "NURSE_ICU",
      name: "RN James (ICU)",
      status: "AVAILABLE",
      location: "Floor 3, ICU Wing",
      capabilities: ["monitoring", "sepsis"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "nurse-ed-1",
      type: "NURSE_ED",
      name: "RN Maria (ED)",
      status: "AVAILABLE",
      location: "Floor 1, Emergency",
      capabilities: ["trauma", "resuscitation", "triage"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "cardiologist-1",
      type: "CARDIOLOGIST",
      name: "Dr. Okonkwo (Cardiology)",
      status: "AVAILABLE",
      location: "Floor 2, Wing B",
      capabilities: ["cardiac", "ecg", "interventional"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "trauma-surgeon-1",
      type: "TRAUMA_SURGEON",
      name: "Dr. Reyes (Trauma Surgery)",
      status: "AVAILABLE",
      location: "Floor 2, Wing A",
      capabilities: ["trauma", "polytrauma", "vascular"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "defib-1",
      type: "DEFIBRILLATOR",
      name: "Defibrillator 1",
      status: "AVAILABLE",
      location: "Floor 1, Emergency",
      capabilities: ["cardiac", "resuscitation"],
      currentPatientId: null,
      utilizationHistory: [],
      createdAt: now,
      updatedAt: now,
    },
  ];
}

function makeVitals(
  hr: number,
  sbp: number,
  dbp: number,
  rr: number,
  spo2: number,
  temp: number,
  gcs: number
) {
  return {
    heartRate: hr,
    systolicBP: sbp,
    diastolicBP: dbp,
    respiratoryRate: rr,
    oxygenSaturation: spo2,
    temperature: temp,
    consciousnessScore: gcs,
    timestamp: Date.now(),
  };
}

export function seedPatients(): Patient[] {
  const now = Date.now();

  // Road accident scenario — 10 patients arrive simultaneously
  const patientsRaw = [
    {
      // Rahul — Heart Attack 🔴 Critical
      id: "pt-1",
      mrn: "MRN-10001",
      age: 45,
      sex: "M" as const,
      condition: "CARDIAC_ARREST" as const,
      conditionDetails: "Rahul — Heart attack, witnessed collapse, CPR in progress",
      vitals: makeVitals(0, 0, 0, 0, 70, 36.5, 3),
      requiresResourceTypes: ["EMERGENCY_BAY", "DEFIBRILLATOR", "CARDIOLOGIST"] as Patient["requiresResourceTypes"],
      requiredCapabilities: ["cardiac", "resuscitation"],
      arrivedAt: now - 2 * 60000,
      estimatedTreatmentDuration: 120 * 60000,
    },
    {
      // Priya — Brain Stroke 🔴 Critical
      id: "pt-2",
      mrn: "MRN-10002",
      age: 38,
      sex: "F" as const,
      condition: "STROKE_ISCHEMIC" as const,
      conditionDetails: "Priya — Brain stroke, sudden left-sided weakness and slurred speech, onset 20 min ago",
      vitals: makeVitals(92, 185, 110, 20, 94, 37.2, 12),
      requiresResourceTypes: ["CT_SCANNER", "ICU_BED"] as Patient["requiresResourceTypes"],
      requiredCapabilities: ["neuro", "monitoring"],
      arrivedAt: now - 2 * 60000,
      estimatedTreatmentDuration: 240 * 60000,
    },
    {
      // Amit — Leg Fracture 🟡 Medium
      id: "pt-3",
      mrn: "MRN-10003",
      age: 28,
      sex: "M" as const,
      condition: "TRAUMA_MAJOR" as const,
      conditionDetails: "Amit — Road accident, compound leg fracture, stable vitals",
      vitals: makeVitals(95, 118, 76, 18, 97, 37.0, 14),
      requiresResourceTypes: ["OPERATING_ROOM", "TRAUMA_SURGEON", "ANESTHESIOLOGIST"] as Patient["requiresResourceTypes"],
      requiredCapabilities: ["trauma"],
      arrivedAt: now - 2 * 60000,
      estimatedTreatmentDuration: 150 * 60000,
    },
    {
      // Neha — Fever 🟢 Low
      id: "pt-4",
      mrn: "MRN-10004",
      age: 22,
      sex: "F" as const,
      condition: "OVERDOSE" as const,
      conditionDetails: "Neha — High fever, mild dehydration, non-critical",
      vitals: makeVitals(88, 110, 72, 16, 98, 39.2, 15),
      requiresResourceTypes: ["EMERGENCY_BAY", "NURSE_ED"] as Patient["requiresResourceTypes"],
      requiredCapabilities: ["general"],
      arrivedAt: now - 2 * 60000,
      estimatedTreatmentDuration: 90 * 60000,
    },
    {
      // Patient 5 — Polytrauma 🔴 Critical
      id: "pt-5",
      mrn: "MRN-10005",
      age: 34,
      sex: "M" as const,
      condition: "POLYTRAUMA" as const,
      conditionDetails: "Road accident — multiple injuries, internal bleeding suspected",
      vitals: makeVitals(125, 80, 50, 28, 91, 37.4, 10),
      requiresResourceTypes: ["OPERATING_ROOM", "TRAUMA_SURGEON", "ICU_BED"] as Patient["requiresResourceTypes"],
      requiredCapabilities: ["trauma", "monitoring"],
      arrivedAt: now - 2 * 60000,
      estimatedTreatmentDuration: 200 * 60000,
    },
    {
      // Patient 6 — Respiratory Failure 🔴 Critical
      id: "pt-6",
      mrn: "MRN-10006",
      age: 60,
      sex: "F" as const,
      condition: "RESPIRATORY_FAILURE" as const,
      conditionDetails: "Road accident — chest crush injury, severe breathing difficulty",
      vitals: makeVitals(110, 95, 65, 32, 82, 37.6, 11),
      requiresResourceTypes: ["ICU_BED", "VENTILATOR"] as Patient["requiresResourceTypes"],
      requiredCapabilities: ["ventilation", "respiratory"],
      arrivedAt: now - 2 * 60000,
      estimatedTreatmentDuration: 360 * 60000,
    },
    {
      // Patient 7 — Sepsis 🔴 Critical
      id: "pt-7",
      mrn: "MRN-10007",
      age: 55,
      sex: "M" as const,
      condition: "SEPSIS" as const,
      conditionDetails: "Road accident — open wound infection, septic shock developing",
      vitals: makeVitals(118, 75, 42, 30, 90, 39.9, 10),
      requiresResourceTypes: ["ICU_BED", "NURSE_ICU"] as Patient["requiresResourceTypes"],
      requiredCapabilities: ["sepsis", "monitoring"],
      arrivedAt: now - 2 * 60000,
      estimatedTreatmentDuration: 300 * 60000,
    },
    {
      // Patient 8 — Burns 🟡 Medium
      id: "pt-8",
      mrn: "MRN-10008",
      age: 42,
      sex: "F" as const,
      condition: "BURNS_MAJOR" as const,
      conditionDetails: "Road accident — vehicle fire, 30% body burns",
      vitals: makeVitals(105, 100, 68, 22, 95, 38.5, 13),
      requiresResourceTypes: ["OPERATING_ROOM", "ICU_BED"] as Patient["requiresResourceTypes"],
      requiredCapabilities: ["trauma", "monitoring"],
      arrivedAt: now - 2 * 60000,
      estimatedTreatmentDuration: 240 * 60000,
    },
    {
      // Patient 9 — Anaphylaxis 🟡 Medium
      id: "pt-9",
      mrn: "MRN-10009",
      age: 19,
      sex: "M" as const,
      condition: "ANAPHYLAXIS" as const,
      conditionDetails: "Road accident — bee sting exposure, allergic reaction",
      vitals: makeVitals(100, 90, 60, 24, 93, 37.8, 14),
      requiresResourceTypes: ["EMERGENCY_BAY", "NURSE_ED"] as Patient["requiresResourceTypes"],
      requiredCapabilities: ["resuscitation"],
      arrivedAt: now - 2 * 60000,
      estimatedTreatmentDuration: 60 * 60000,
    },
    {
      // Patient 10 — Hemorrhagic Stroke 🔴 Critical
      id: "pt-10",
      mrn: "MRN-10010",
      age: 70,
      sex: "M" as const,
      condition: "STROKE_HEMORRHAGIC" as const,
      conditionDetails: "Road accident — head trauma, hemorrhagic stroke, unconscious",
      vitals: makeVitals(58, 195, 120, 10, 88, 37.1, 5),
      requiresResourceTypes: ["OPERATING_ROOM", "ICU_BED"] as Patient["requiresResourceTypes"],
      requiredCapabilities: ["neuro", "monitoring"],
      arrivedAt: now - 2 * 60000,
      estimatedTreatmentDuration: 300 * 60000,
    },
  ];

  return patientsRaw.map((p) => ({
    ...p,
    triageScore: computeTriageScore(p.condition, p.vitals, p.arrivedAt),
    vitalsHistory: [p.vitals],
    status: "WAITING" as const,
    allocatedResources: [],
    dischargedAt: null,
    treatmentStartedAt: null,
  }));
}

export function seedAgents(resources: Resource[]): ResourceAgent[] {
  return resources.map((r) => ({
    id: `agent-${r.id}`,
    resourceId: r.id,
    state: r.status === "MAINTENANCE" ? ("MAINTENANCE" as const) : ("IDLE" as const),
    currentBid: null,
    currentPatientId: null,
    performanceMetrics: {
      totalAllocations: 0,
      bidsSubmitted: 0,
      bidsWon: 0,
      averageBidScore: 0,
    },
  }));
}

export function generateRandomPatient(): Omit<
  Patient,
  "triageScore" | "vitalsHistory" | "status" | "allocatedResources" | "treatmentStartedAt" | "dischargedAt"
> {
  const conditions = [
    "CARDIAC_ARREST",
    "TRAUMA_MAJOR",
    "STROKE_ISCHEMIC",
    "STROKE_HEMORRHAGIC",
    "SEPSIS",
    "RESPIRATORY_FAILURE",
    "BURNS_MAJOR",
    "POLYTRAUMA",
    "ANAPHYLAXIS",
    "OVERDOSE",
  ] as const;

  const resourceMap: Record<string, { types: string[]; caps: string[] }> = {
    CARDIAC_ARREST: {
      types: ["EMERGENCY_BAY", "DEFIBRILLATOR", "CARDIOLOGIST"],
      caps: ["cardiac", "resuscitation"],
    },
    TRAUMA_MAJOR: {
      types: ["OPERATING_ROOM", "TRAUMA_SURGEON", "ANESTHESIOLOGIST"],
      caps: ["trauma"],
    },
    STROKE_ISCHEMIC: { types: ["CT_SCANNER", "ICU_BED"], caps: ["neuro", "monitoring"] },
    STROKE_HEMORRHAGIC: {
      types: ["OPERATING_ROOM", "ICU_BED"],
      caps: ["neuro", "monitoring"],
    },
    SEPSIS: { types: ["ICU_BED", "NURSE_ICU"], caps: ["sepsis", "monitoring"] },
    RESPIRATORY_FAILURE: {
      types: ["ICU_BED", "VENTILATOR"],
      caps: ["ventilation", "respiratory"],
    },
    BURNS_MAJOR: {
      types: ["OPERATING_ROOM", "ICU_BED"],
      caps: ["trauma", "monitoring"],
    },
    POLYTRAUMA: {
      types: ["OPERATING_ROOM", "TRAUMA_SURGEON", "ICU_BED"],
      caps: ["trauma", "monitoring"],
    },
    ANAPHYLAXIS: { types: ["EMERGENCY_BAY", "NURSE_ED"], caps: ["resuscitation"] },
    OVERDOSE: { types: ["EMERGENCY_BAY", "NURSE_ED"], caps: ["general"] },
  };

  const condition = conditions[Math.floor(Math.random() * conditions.length)];
  const res = resourceMap[condition];
  const ages = [18, 25, 34, 45, 52, 61, 67, 73, 81];
  const mrnId = Math.floor(10000 + Math.random() * 90000);

  const vitals = makeVitals(
    50 + Math.floor(Math.random() * 100),
    60 + Math.floor(Math.random() * 120),
    40 + Math.floor(Math.random() * 60),
    8 + Math.floor(Math.random() * 24),
    80 + Math.floor(Math.random() * 20),
    35.5 + Math.random() * 4,
    3 + Math.floor(Math.random() * 13)
  );

  return {
    id: crypto.randomUUID(),
    mrn: `MRN-${mrnId}`,
    age: ages[Math.floor(Math.random() * ages.length)],
    sex: ["M", "F"][Math.floor(Math.random() * 2)] as "M" | "F",
    condition,
    conditionDetails: `${condition.replace(/_/g, " ")} — auto-generated patient`,
    vitals,
    requiresResourceTypes: res.types as Patient["requiresResourceTypes"],
    requiredCapabilities: res.caps,
    arrivedAt: Date.now(),
    estimatedTreatmentDuration: (60 + Math.floor(Math.random() * 240)) * 60000,
  };
}
